### ISSUE TITLE
Government Policy Handling

### ISSUE THREAD

**Issue by MornevanHeerden** [COS214-Project-2024/Team-11#4]
How the government policies are implemented and how this affects the statistics such as income, satisfaction etc. The frontend, unit testing, doxygen etc..

**Comment by herrie732** [comment]
Implemented 3 different policies as the command pattern. BoostEducation, BoostPolice, BoostHealthcare

**Comment by herrie732** [comment]
Planning to add more but there is sufficient government policies currently
